insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (1, 'Avon Products, Inc', 'PH50723', 'Dasha', 'kchedgey0@admin.ch');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (2, 'Rebel Distributors Corp', 'PH55014', 'Banayoyo', 'pklossek1@spotify.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (3, 'Tarte, Inc', 'PH36315', 'Monrovia', 'tdahlborg2@ebay.co.uk');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (4, 'Pharmacia and Upjohn Company', 'PH98012', 'Sidomulyo', 'cmenauteau3@so-net.ne.jp');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (5, 'Pfizer Labs, Division of Pfizer Inc', 'PH63575', 'Tomas', 'limpett4@biblegateway.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (6, 'Eon Labs, Inc.', 'PH05008', 'Papilawe', 'gadrian5@usatoday.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (7, 'King Bio Inc.', 'PH58511', 'El Paisnal', 'mbraun6@etsy.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (8, 'Amneal-Agila, LLC', 'PH18068', 'Xincheng', 'rbosse7@baidu.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (9, 'Parnell Pharmaceuticals Inc', 'PH01884', 'Almaguer', 'okief8@stumbleupon.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (10, 'AvKARE, Inc.', 'PH91573', 'Hällefors', 'ckolis9@netscape.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (11, 'Rebel Distributors Corp', 'PH32245', 'Strunino', 'dfirtha@cam.ac.uk');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (12, 'Cardinal Health', 'PH49525', 'Junaynat Raslān', 'srubinfeldb@dion.ne.jp');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (13, 'Newton Laboratories, Inc.', 'PH02611', 'Tsimkavichy', 'rianittic@angelfire.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (14, 'Actavis Elizabeth LLC', 'PH65272', 'Schiedam postbusnummers', 'ccrabd@bbc.co.uk');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (15, 'Harris Pharmaceutical, Inc.', 'PH77309', 'Dadeldhurā', 'gwastlinge@who.int');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (16, 'Dr.Reddy''s Laboratories Limited', 'PH75736', 'Malunda', 'mjordanf@sciencedirect.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (17, 'Unifirst First Aid Corporation', 'PH30960', 'Basoko', 'wbellinig@shinystat.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (18, 'Delon Laboratories (1990) Ltd', 'PH53967', 'Pulap', 'gbusfieldh@spotify.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (19, 'Uriel Pharmacy Inc.', 'PH97073', 'Göteborg', 'dangricki@businesswire.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (20, 'Procter and Gamble Manufacturing Company', 'PH39757', 'Krasnoarmeysk', 'jagnewj@nhs.uk');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (21, 'Ventura Corporation LTD.', 'PH49132', 'Rochester', 'omichielk@simplemachines.org');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (22, 'Nelco Laboratories, Inc.', 'PH10153', 'Sua', 'tmartinollil@economist.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (23, 'DAVA Pharmaceuticals, Inc.', 'PH65993', 'Xiaohe', 'abrendishm@bloomberg.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (24, 'Nelco Laboratories, Inc.', 'PH14565', 'Nyazura', 'aleynaghn@amazonaws.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (25, 'PD-Rx Pharmaceuticals, Inc.', 'PH56842', 'Franco da Rocha', 'cstoniero@diigo.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (26, 'Boots Retail USA Inc', 'PH02051', 'Salogon', 'deggerp@jiathis.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (27, 'Uriel Pharmacy Inc.', 'PH77698', 'Puyan', 'phrinchenkoq@github.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (28, 'REMEDYREPACK INC.', 'PH48106', 'Palestina', 'tkonneker@amazon.co.jp');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (29, 'Sanum Kehlbeck GmbH & Co. KG', 'PH64965', 'Huamali', 'pmeachans@netlog.com');
insert into pharmacies (pharmacy_id, name, license_no, city, contact_email) values (30, 'mybody', 'PH73453', 'Dongpu', 'hkimmelt@boston.com');
